ServiceInnovationLab/FSD

.travis.yml, README.md, package.json, src/components/Header.js, src/components/ServiceCategories.js, src/pages/index.js, yarn.lock
Partially created travis setup, a few autoformat things, added yarn package
=> [WIP] CI Setup

src/App.js, src/components/ServiceCategories.js, src/contexts/category-context.js, src/pages/index.js, src/utilities/__tests__/api.test.js
This is a branch off of the select category branch to specifically apply the Context API as the solution for sharing the category between pages.
=> Category context

src/__mocks__/addressLatLng.js, src/__mocks__/dataPoint.js, src/pages/index.js, src/utilities/__tests__/api.test.js, src/utilities/__tests__/geography.test.js, src/utilities/__tests__/url.test.js, src/utilities/api.js, src/utilities/url.js
Implements full test coverage on utility files.
closes #16
=> Utility test coverage

src/assets/scss/theme/_a.scss, src/assets/scss/theme/_base.scss, src/assets/scss/theme/_body.scss, src/assets/scss/theme/_breakpoints.scss, src/assets/scss/theme/_button.scss, src/assets/scss/theme/_colors.scss, src/assets/scss/theme/_footer.scss, src/assets/scss/theme/_h.scss, src/assets/scss/theme/_header.scss, src/assets/scss/theme/_input.scss, src/assets/scss/theme/_main.scss, src/assets/scss/theme/_mixins.scss, src/assets/scss/theme/_reset.scss, src/assets/scss/theme/_selection.scss, src/components/Header.js, src/containers/Home.js
=> Basic theme with some variables and mixins

src/components/search-form.js, src/containers/auto-suggest.js, src/pages/index.js, src/pages/service.js
=> watch url and update ui using componentDidUpdate

.gitignore
Just a quick update to .gitignore in preparation for adding cucumber. Submitted separately so it's easy to approve.
=> Update .gitignore for Cucumber

src/components/social-sharebar.js, src/containers/auto-suggest.js, src/pages/index.js
...and adds a small fix for having a unique key because React
close #54
=> Autopopulates location field from url

src/assets/scss/components/_map.scss, src/components/search-form.js, src/pages/service.js
- Change "Reset Form" to "Reset Search" close #76 
- Ensure Autosuggest is not covered by map close #63 
- Only show map for providers with location close #68
=> Add quick changes from demo

features/shared_objects/host.js, features/step_definitions/main-page-steps.js
I don't usually write Cucumber tests in JavaScript so I'm working on my style. I'm looking for feedback on better JavaScript style and whether this is an improvement in the readability of the tests.
One thing I'm finding difficult is that everything is a JavaScript `promise` which has to be resolved with `.then` before I can test the values, so if there's an easier syntax I'd be keen to learn it.
=> [Low] Refactoring Cucumber/JS for better readability

.circleci/config.yml
=> add run to npm scripts

src/components/social-sharebar.js
Auto corrected by following Lint Javascript prefer-template
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/FSD/javascript_lint_configs/58383) to configure it on awesomecode.io
=> Auto corrected by following Lint Javascript prefer-template

src/components/social-sharebar.js
Auto corrected by following Lint Javascript object-shorthand
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/FSD/javascript_lint_configs/58375) to configure it on awesomecode.io
=> Auto corrected by following Lint Javascript object-shorthand

src/utilities/api.js
Auto corrected by following Lint Javascript no-else-return
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/FSD/javascript_lint_configs/58611) to configure it on awesomecode.io
=> Auto corrected by following Lint Javascript no-else-return

src/components/search-criteria.js
Added Search Criteria Summary component
Closed #75
=> Added Search Criteria Summary component

src/components/service-provider.js
Added external link on the classification.
Closes #74
=> Added external link on the classification

src/components/search-criteria.js, src/pages/index.js
Added search criteria to be displayed.
=> Added search criteria to be displayed.

features/helpers/get-attribute-for-input.js, features/helpers/get-input-element.js, features/step_definitions/main-page-steps.js, src/App.js, src/components/footer.js, src/components/header.js, src/components/search-criteria.js, src/components/search-form.js, src/components/service-categories.js, src/components/service-details.js, src/components/service-map-marker.js, src/components/service-provider.js, src/components/social-sharebar.js, src/containers/auto-suggest.js, src/containers/list-of-service-providers.js, src/containers/page.js, src/containers/search-container.js, src/pages/index.js, src/pages/service.js, src/serviceWorker.js, src/utilities/__tests__/geography.test.js, src/utilities/__tests__/url.test.js, src/utilities/addressfinder.js, src/utilities/api.js, src/utilities/query-string.js, src/utilities/url.js
Auto corrected by following Format Javascript Code
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/FSD/javascript_format_config) to configure it on awesomecode.io
=> Auto corrected by following Format Javascript Code

src/utilities/addressfinder.js
=> don't fetch "regions"

features/github-pages.feature, features/step_definitions/url-steps.js, src/App.js
=> Use HashRouter to satisfy Github Pages

src/assets/scss/theme/_button.scss
Added padding to the buttons (for mobile).
Closes #130
=> Added padding to the buttons.

src/components/search-form.js
Changed Organisations to singular.
Closes #150
=> Changed Organisations to singular.

src/assets/scss/theme/_input.scss
Added media query to the search boxes hoping that this will solve the issue on Apple devices.
Closes #149
=> Added media query to the search boxes

src/assets/scss/theme/_input.scss
Changed the width of the textbox.
=> Changed the width of the textbox.

src/utilities/api.js
Change default search results limit to 50
closes #158
=> Change default search result limit to 50

src/assets/scss/components/_accordion.scss
Added margins to make the arrows not overlap text.
Closes #163
=> Added margins to make the arrows not overlap text.

features/search-examples.feature, features/search.feature, features/service-page.feature, features/service-results.feature, features/step_definitions/search-steps.js, selenium-cucumber-js.json, src/utilities/api.js
Improves reliability of cucumber tests using the address autosuggest box
=> Makes address suggestion searches more robust

src/assets/scss/components/_search.scss, src/components/search-form.js, src/containers/auto-suggest.js
Added aria-labels to improve accessibility score.
**Was:**
**Current: **
Closes #195
=> Added aria-labels

src/pages/index.js
Changed unique search from "provider name" to "published phone".
Closes #216
=> Changed unique search from "provider name" to "published phone".

src/components/search-criteria.js, src/pages/index.js
Added region to props & search criteria.
Closes #200
=> Added region to props & search criteria.

.circleci/config.yml
This will be public in the javascript, and isn't a real secret secret
=> Added dpeloyment key for Address finder

example.env, public/index.html
Improved CSP
Added CKAN UAT to example env for reference
=> add data.gov UAT to example.env

src/components/footer.js
- Send email to updates@familyservices.govt.nz
- Populate subject line with 'Feedback on mobile site'
=> Correct email and subject line in mailto

src/components/search-criteria.js, src/pages/index.js
If the location you've input isn't being used for the search, let's not show it.
Closes #382
=> Don't show location if not searching with it

.babelrc
Change .babelrc to support IE11
=> Support IE 11

src/assets/scss/utilities/_mui_overrides.scss, src/components/map-list-toggle.js, src/components/save-contact.js, src/components/search-criteria.js, src/components/service-header.js, src/components/service-provider-result.js, src/components/service-provider.js, src/containers/list-of-service-providers.js, src/pages/service.js, src/utilities/api.js, src/utilities/providerDetails.js
- Oops, I broke the 'save contact' function in #388 - this fixes it
- Some final requests from Paul
- Map the full provider details and pass them around, rather than passing them around in the components
<details>
<summary>Screenshots</summary>
</details>
<details>
<summary>Request from client</summary>
Some last wishes: can the colors for distance,  List/map and More Details and Save Contact match Search/Reset Search so that the selected is dark blue. For the List Map and More Details and Save Contact can they present in this order i.e. List  Map and More Details  Save Contact.
</details>
=> fix save contact function, make more things blue, move things around

src/assets/scss/utilities/_flex.scss, src/components/service-provider-result.js
=> Justify buttons

.circleci/config.yml, package-lock.json
=> Fix test failure
